name: PR requirement

on:
    pull_request_target:
        types: [opened, synchronize, reopened]
        branches: [main]

jobs:
  build-next:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm i
      - name: Build FE
        run: npm run build