name: PR requirement

on:
    pull_request_target:
        types: [opened]
        branches:
            - main

jobs:
  build-fe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Build FE
        run: npm run build