name: PR requirement

on:
    pull_request_target:
        types: [opened, synchronize, reopened]
        branches: [main]

jobs:
  build-next:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
            ref: ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        run: npm i
      - name: Build FE
        run: npm run build
      - name: Build storybook
        run: npm run build-storybook